name = "ChrisJuliaRegistry"
uuid = "d94e65b8-b6ba-4012-81ca-70cc75ad30d3"
repo = "https://github.com/chowerth/ChrisJuliaRegistry.git"
description = "Chris's private registry"

[packages]
55b8f459-a959-4a23-ae1e-fc49525a582e = { name = "ChrisTestPkg", path = "C/ChrisTestPkg" }
